name:                aoclib
version:             0.1.0.0
license:             BSD3
author:              "Emily Curry"
maintainer:          "emily@curry.sh"
copyright:           "2023 Emily Curry"

dependencies:
- base >= 4.9 && < 5
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  aoclib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoclib
