name:                aoc01
version:             0.1.0.0
license:             BSD3
author:              "Emily Curry"
maintainer:          "emily@curry.sh"
copyright:           "2023 Emily Curry"

dependencies:
- base >= 4.7 && < 5
- aoclib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  aoc01:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
